name: First workflow
on: [pull_request]
jobs:
 Explore-GitHub-Actions:
   runs-on: ubuntu-latest
   steps:
   - name: Step 1
     run: echo "🎉 This job was triggered automatically Step 1!"
   - name: Step 2
     run: echo "🎉 This job was triggered automatically Step 2!"
   - name: Comment on pull_request
     uses: thollander/actions-comment-pull-request@v1
     with:
          message: |
               Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    

 Explore-GitHub-Actions_2:
   runs-on: ubuntu-latest
   needs: Explore-GitHub-Actions
   steps:
     - run: echo "🎉 This job was triggered automatically second time!"
